### ISSUE TITLE
No Scroll in description pane

### ISSUE THREAD

**Issue by akashdoppalapudi** [gangofdev/interactive-tutor#12]
**Describe the bug**
The content inside description page in not scrollable

**To Reproduce**
1. Go to 'intutor-page'
2. Click on 'description tab'
3. Try to scroll down
4. Notice the content is not scrollable

**Expected behavior**
The description content should be scrollable

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Chromium
 - Version 106.0.5249.91

**Comment by notshriram** [comment]
Yup 
Can reproduce this
